### ISSUE TITLE
При старте вылетает исключение

### ISSUE THREAD

**Issue by kudryaA** [bi-te/bTaskManager#12]
![image](https://user-images.githubusercontent.com/16844328/105408419-9a807a80-5c37-11eb-90f2-deb7b90acc66.png)

**Comment by kudryaA** [comment]
Выводи какое-то более понятное сообщение, к примеру что нету сохраненных тасок.

**Comment by bi-te** [comment]
https://github.com/bi-te/bTaskManager/pull/17#issue-560407370
